version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rms
      - POSTGRES_USER=rms
      - POSTGRES_PASSWORD=rms
  web:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
